---
# tasks file for for the gentoo role

- include: 0-partitioning.yml
- include: 1-stage3.yml
- include: 2-chroot.yml
- include: 3-kernel.yml
# - include: 4-bootloader.yml

# - include: 5-extras.yml
# - include: 6-settings.yml

# - include: keys.yml



# - name: Deploy User's Authorized Key to Root
#   authorized_key: user=root key="{{ lookup('file', pubkey) }}"

# - include: storage.yml

# - stat: path=/tmp/filesystem_completed
#   register: filesystem_completed

# - include: filesystem.yml
#   when: filesystem_completed.stat.exists == False

# - include: kernel.yml
# - include: networking.yml
# - include: system.yml
# - include: packages.yml
# - include: reboot.yml

