---
# pubkey: ~/.ssh/id_rsa.pub
# main_disk: /dev/sda
# root_size: 95%FREE
# swap_size: 2048m
# vg_name:   main
# fstype: ext4
# force_format: no
# mirror: http://mirror.mcs.anl.gov/pub/gentoo
# timezone: Europe/Amsterdam
# domain: met.tfoundry.com
# kernel: config-3.13.0-24-generic
# make_opts: -j8
# management_interface: "{{ ansible_default_ipv4.interface }}"
# root_passwd: gentoo-root
# gateway: "{{ ansible_default_ipv4.gateway }}"
# netmask: "{{ ansible_default_ipv4.netmask }}"

ssh_port: 22
disk_name: /dev/sda
swapsize: 8GB
